import Footer from '@/components/layout/footer/pages';
import Header from '@/components/layout/header/pages';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import { ReactQueryClientProvider } from './ReactQueryClientProvider';
import './globals.css';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryClientProvider>
            <html lang="en">
                <body style={{ fontFamily: 'Roboto, var(--font-geist-sans)', width: '100vw', height: '100vh' }}>
                    <AppRouterCacheProvider>
                        <Header />
                        {children}
                        <Footer />
                    </AppRouterCacheProvider>
                </body>
            </html>
        </ReactQueryClientProvider>
    );
}
